# fly.toml app configuration file generated for devnout-app on 2023-05-16T19:33:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "devnout-app"
primary_region = "mad"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
